<a href="https://colab.research.google.com/github/sen6eiiiii/Deep-learning-fundamentals-/blob/main/00_pytorch_fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:

import torch
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


In [97]:
!mkdir /content/drive

mkdir: cannot create directory ‘/content/drive’: File exists


In [106]:
import os

os.mkdir("/content/drive/MyDrive/Colab Notebooks/00_pytorch_fundamentals")

FileExistsError: [Errno 17] File exists: '/content/drive/MyDrive/Colab Notebooks/00_pytorch_fundamentals'

In [ ]:
##introduction to Tensors

## tensors are a way to reprenent data

#creating tensors#pytorch tensor are created using torch.tensor


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#back as a python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR= torch.tensor([[[2,1,3],
 [4,5,6],
  [7,8,9]]])
TENSOR

tensor([[[2, 1, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
Why random tensors
Random tensors are important because the very many neural network learn is that they start with tensor full of random numbers and then adjust those randome numbers to better represent the data.
Start with random numbers ->look at data->update random numbers ->look at data-> update random numbers

In [ ]:
# Create  a random tensor of size(3,4)
random_tensor =torch.rand(3,4)
#random_tensor =torch.rand(10,10)
random_tensor

tensor([[0.1114, 0.9606, 0.7001, 0.5237],
        [0.7068, 0.0963, 0.7051, 0.9510],
        [0.2409, 0.1468, 0.1838, 0.1726]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor =torch.rand(size=(224,224,3))#height, width, colour channel(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

the take away here is that any images can be represented in a tensor and can be divided in 3 colour channels which are redgreen and blue as these 3 colours can form any colurs

Zeros and ones

In [ ]:
# atensor of all zeros
zeros= torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones (size= (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
### Creating a range of tewnsor and tensors like

In [ ]:
one_to_ten=torch.arange(start=1, end= 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#create tensors like
ten_zeros= torch.zeros_like (input = one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The tensor data tyoe are onse of the big errors in Pythorch
      1 tensor not right data tyoe
      2 tensor not right shape
      3 tensor not right device

In [ ]:
#float 32 tensors
float_32_tensor= torch.tensor([3.0,6.0,9.0] ,
                               dtype=None,# data type is the tensor (e.g float 32 or float 16)
                               device= None,
                                requires_grad =False )
float_32_tensor




tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor= float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor* float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype= torch.long
                           )
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

#getting information from tensors

Tensors not right datatyp -  to do get datatype from a tensor, can user `tensor.dtype`
Tensors not right shap  - to get shape from a tensor, can use `tensor.shape `
Tensor not on the right device - to get device- to get device from a tensor , can use `tensor.device`

In [ ]:
some_tensor =torch.rand(3,4)
some_tensor

tensor([[0.0495, 0.2279, 0.7531, 0.6162],
        [0.6584, 0.5073, 0.5667, 0.8881],
        [0.0406, 0.9409, 0.8363, 0.9066]])

In [ ]:
#find some details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype }")
print(f"Tensor is not in the right shape{some_tensor.shape } ")
print(f"What device is on {some_tensor.device} ")
some_tensor

tensor([[0.0495, 0.2279, 0.7531, 0.6162],
        [0.6584, 0.5073, 0.5667, 0.8881],
        [0.0406, 0.9409, 0.8363, 0.9066]])
Datatype of tensor: torch.float32
Tensor is not in the right shapetorch.Size([3, 4]) 
What device is on cpu 


tensor([[0.0495, 0.2279, 0.7531, 0.6162],
        [0.6584, 0.5073, 0.5667, 0.8881],
        [0.0406, 0.9409, 0.8363, 0.9066]])

## Manipulation tensors ( tensor operations )
Tensors operations include )
Addition
subtraction
Manpulation
s



In [ ]:
#adding a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multyplying one
tensor = torch.tensor([1, 2, 3])
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#Try out pytorch inbuild funtion
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication
Two main ways of performing multiplications in neural netwrork and deep learning
1 element-wise multiplication
2 matrix multiplicatioon(dot product)

In [ ]:
#element wise
tensor
print(tensor,"*" , tensor )
print(f"Equals:{tensor* tensor }")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
value = 0
for i  in range(len(tensor )):
  value+= tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learnings is shape errors
there are two mains rules that performaning metrix mult needs to sutisfy
1 inner dimension must match ]
2:

In [ ]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [ ]:
#
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

result = torch.mm(tensor_A, tensor_B.T)
print(result)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


To fix a tensor shape issues, we can manipuliate the shape of one fo our rensors using a transpose
A tanspose switches the axes the axes or dimension of a given tensor

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
## Matrix multiplication works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")

print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")

print("Multiplying...")

print(torch.mm(tensor_A, tensor_B.T).shape)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying...
torch.Size([3, 3])


Finding the min, max, mean, sum, etc (tensor agregation )

In [ ]:
#create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# finding the mean
torch.min(x) ,x.min()

(tensor(0), tensor(0))

In [ ]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#finding the mean
#the torch.mean() function requires a tensor of a float32 datatype to work

torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#finding the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the position in tensor that has the minimul value in admin and return  the index position (starting position where the minimum value accord )

x.argmin()

tensor(0)

In [ ]:
#find the position which as the max value in the tensor which is argmax
x.argmax()

tensor(9)

In [ ]:
x_stacked= torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

#reshaping , stacking , squeezing and unqueering tensors
reshaping an input tensor to a defined shap
return a view of an input tensor of a certain shape but keep the same memory as the original tensor
staking combine multiple tensors on top of each other (vstack) or side by side
Squeexe remove all `1` dimensions from a tensor
Unsqueeze - add a `1 ` dimension to a target tensor
permute - return a view of the input with demensions permuted (swapped) in a certain way


In [ ]:
#lets creat a tensor
import torch
x = torch.arange(1.,9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [ ]:
#add an extra dimenstion
x_reshaped = x.reshape(1,8)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
#Change the view
z=x.view(1,8)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [ ]:
#changing z changes x because a view of a tensor shares the same memory as the original input
z[:,0]= 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor
x=torch.zeros(2,1,2,1,2)
x.size()
y= torch.squeeze(x)
y.size()
y= torch.squeeze(x,1)
y.size()


torch.Size([2, 2, 1, 2])

In [ ]:
print(f"Previous tensor{x_reshaped}")
print(f"Previous shape {x_reshaped.shape}")
#remove exra dimension from x_reshaped
x_squeezed =x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape {x_squeezed.shape}")


Previous tensortensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape torch.Size([1, 8])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
New shape torch.Size([8])


In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([8])

In [ ]:
#torch.unsqueez add a single dimension to a target tensor
print(f"Previous tensor{x_squeezed}")
print(f"Previous shape {x_squeezed.shape}")
#remove exra dimension from x_reshaped
x_unsqueezed =x_reshaped.unsqueeze(dim =0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape {x_unsqueezed.shape}")


Previous tensortensor([5., 2., 3., 4., 5., 6., 7., 8.])
Previous shape torch.Size([8])

New tensor: tensor([[[5., 2., 3., 4., 5., 6., 7., 8.]]])
New shape torch.Size([1, 1, 8])


In [ ]:
#torch. permute- rearranges the dimension of a target tensor in a specify order
x_original = torch.rand(size=(224,224,3))#high width and colour channel
# permute the original tensor to rearange the access of the dimension
x_permuted = x_original.permute(2, 0,1 )
print(f"Previous tensor{x_original.shape}")
print(f"Previous shape {x_permuted.shape}")# this is colour channel high width



Previous tensortorch.Size([224, 224, 3])
Previous shape torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]=5433

In [ ]:
##indexing(selecting data from tensors)

indexing with pytorch is similar  to Indexing with Numpy

In [ ]:
# Crate a tensor
import torch
x= torch.arange (1,10).reshape(1,3,3)
x,x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
#can use also : to select "all " of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
#get all the values from 0 and 1st dimension but only index 1 of 2nd dimensio
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#get all the values of the 0 dimension but only the 1 index values of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
#get index 0 of 0th and 1st dimension and all values from second dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
#Pytorch tensors and numpy

numpy is popular scientific python numerical computing library
and because of this pytorch as functionality to intect with
Data in numpy want in pytorch tensor



In [ ]:
# Numpy array to tensor
import torch
import numpy as np
array= np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#change the value of array , what will this do to tensor
array=array +1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numay array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#REPRODUCBILIY ( trying to take random out of random  )
i short how nn learns
start with random numbers->tensor operations->update random numbers to try to make them better representation of the data again again and again
to reduce the randomness in nn and pytorch comes the concepts
**random seed **
Essentiually what the random seed does is flavour the randomness

In [ ]:
torch.rand(3,3)

tensor([[0.9358, 0.5550, 0.3319],
        [0.1288, 0.8635, 0.5957],
        [0.4011, 0.1023, 0.3966]])

In [ ]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B= torch.rand(3,4)
print(random_tensor_A )
print(random_tensor_B )
print(random_tensor_A == random_tensor_B )

tensor([[0.0370, 0.1969, 0.2488, 0.3019],
        [0.0845, 0.3062, 0.7925, 0.6993],
        [0.1874, 0.8274, 0.2309, 0.5459]])
tensor([[0.3250, 0.4940, 0.1849, 0.5490],
        [0.8526, 0.2629, 0.4969, 0.6449],
        [0.4856, 0.8441, 0.3422, 0.2451]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#let's make some random bots reproducible tensors
import torch
#set the random seed
RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D )
print(random_tensor_C== random_tensor_D )


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##running tensors and PyTorch objects on the GPUs (and making faster computation)

GPus = faster computation on numbers


In [ ]:
#ceck for gpu access with pytorch
import torch
torch.cuda.is_available


<function torch.cuda.is_available() -> bool>

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available () else "cpu "
device


'cuda'

In [ ]:
# count the number of devices
torch.cuda.device_count()

1

## putting tensors and (models) on the gpu
The reason we want our tensors on the gpu is becauseusing gpu result in faster computation
gpu are good at doing numerical calculations like the one we saw above


In [ ]:
#create a tansor
tensor= torch.tensor([1,2,3])
#tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to gpu if available
tensor_on_gpu =  tensor.to(device)
tensor_on_gpu



tensor([1, 2, 3], device='cuda:0')

Moving tensors back to the cpu


In [ ]:
# if tensor is on GPU can't runsform into numpy
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#to fix the GPU tensor with Numpy issue , we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')